{{- if not .Values.existingSecret }}
{{- $fullName := include "pgadmin.fullname" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}
  namespace: {{ include "pgadmin.namespaceName" . }}
  labels:
    {{- include "pgadmin.labels" . | nindent 4 }}
type: Opaque
data:
{{- $previous := lookup "v1" "Secret" (include "pgadmin.namespaceName" .) (include "pgadmin.fullname" .) | mergeOverwrite (dict "data" dict) }}
  password: {{ coalesce .Values.env.password (default "" $previous.data.password | b64dec) (now | unixEpoch | sha256sum | b64enc | trunc 12) | b64enc | quote }}
{{- end }}
